---
driver_plugin: vagrant

platforms:
- name: fedora-18
  driver_config:
    box: sm-fedora-18
    box_url: http://sm-config.s3.amazonaws.com/public/linux/sm-fedora-18.box
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box

suites:
- name: default
  run_list:
  - recipe[ipa_server::hosts]
  - recipe[ipa_server::default]
  - recipe[ipa_server::nagios]
- name: replica
  run_list:
  - recipe[ipa_server::hosts]
  - recipe[ipa_server::replica]
  - recipe[ipa_server::nagios]
  attributes:
    ipa_server:
      replica_file: 'file:///vagrant/replica-info-replica-fedora-18.vagrantup.com.gpg'
